export const services: Array<{ title: string; desc: string; img: string; type: string }> = [
  { title: 'Roof & Terraces', desc: 'i1.jpg', img: '/images/i1.jpg', type: 'image' },
  { title: 'Exterior Wall', desc: 'v1.mp4', img: '/videos/v1.mp4', type: 'video' },
  { title: 'Bathroom', desc: 'i2.jpg', img: '/images/i2.jpg', type: 'image' },
  { title: 'Kitchen', desc: 'v2.mp4', img: '/videos/v2.mp4', type: 'video' },
  { title: 'Water Tank', desc: 'i3.jpg', img: '/images/i3.jpg', type: 'image' },
  { title: 'Heatproofing', desc: 'v3.mp4', img: '/videos/v3.mp4', type: 'video' },
  { title: 'Rainwater-harvesting', desc: 'i4.jpg', img: '/images/i4.jpg', type: 'image' },
  { title: 'Warehouse', desc: 'v4.mp4', img: '/videos/v4.mp4', type: 'video' },
  { title: 'Malls', desc: 'i5.jpg', img: '/images/i5.jpg', type: 'image' },
  { title: 'Additional 1', desc: 'v5.mp4', img: '/videos/v5.mp4', type: 'video' },
  { title: 'Additional 2', desc: 'i6.jpg', img: '/images/i6.jpg', type: 'image' },
  { title: 'Additional 3', desc: 'i7.jpg', img: '/images/i7.jpg', type: 'image' },
  { title: 'Additional 4', desc: 'i8.jpg', img: '/images/i8.jpg', type: 'image' },
  { title: 'Additional 5', desc: 'i9.jpg', img: '/images/i9.jpg', type: 'image' },
  { title: 'Additional 6', desc: 'i10.jpg', img: '/images/i10.jpg', type: 'image' },
  { title: 'Additional 7', desc: 'i11.jpg', img: '/images/i11.jpg', type: 'image' },
  { title: 'Additional 8', desc: 'i12.jpg', img: '/images/i12.jpg', type: 'image' },
];